### ISSUE TITLE
刚才git pull，客户端升级到3.6.1之后。异常情况。

### ISSUE THREAD

**Issue by cfcboy** [breakwa11/shadowsocks-rss#119]
不知道是git pull的问题。还是客户端的问题。。升级之后。配置都没有改。

GOOGLE邮箱打不开，TUMBLR图片不显示。。

其它网站图片好像也打不开。

**Comment by breakwa11** [comment]
有log么

**Comment by Balanky** [comment]
我的情况跟 @cfcboy 差不多，在服务端还没git pull前，更新3.6后还是正常的，服务端git pull后就出现状况了，换到之前的版本也一样。以下是log
[2015-10-27 21:27:34] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:46671
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2015-10-27 21:30:16] failed to recv data in handshakeReceive2Callback

**Comment by Balanky** [comment]
Android端是正常的。

**Comment by cfcboy** [comment]
@breakwa11
 [2015-10-27 21:52:08] System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 Shadowsocks.Obfs.AuthSimple.ClientPreEncrypt(Byte[] plaindata, Int32 datalength, Int32& outlength)
   在 Shadowsocks.Controller.Handler.RemoteSend(Byte[] bytes, Int32 length, Int32 tcp_protocol, Int32 obfs_max)
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:52:08]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void runTryCode(System.Object)
 0 0 Void ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
@Balanky 和他情况应该是一样。。换旧版本也没用。

**Comment by Balanky** [comment]
[2015-10-27 21:30:42] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:31:09] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:31:57] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:32:02] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:32:03] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:32:03] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:32:03] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-27 21:38:40] [Warn]Proxy server [SSR(xxx.xxx.xxx.xxx)] connection timeout
[2015-10-27 21:38:46] System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Listener.AcceptCallback(IAsyncResult ar)
[2015-10-27 21:38:50] [Warn]Proxy server [SSR(xxx.xxx.xxx.xxx)] connection timeout
[2015-10-27 21:39:01] [Warn]Proxy server [SSR(xxx.xxx.xxx.xxx)] connection timeout
[2015-10-27 21:39:24] [Warn]Proxy server [SSR(xxx.xxx.xxx.xxx)] connection timeout
[2015-10-27 21:40:46] System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Listener.AcceptCallback(IAsyncResult ar)
[2015-10-27 21:42:47] [Warn]Proxy server [SSR(xxx.xxx.xxx.xxx)] connection timeout
[2015-10-27 21:45:47] failed to recv data in handshakeReceive2Callback
[2015-10-27 21:46:26] [Warn]Proxy server [SSR(xxx.xxx.xxx.xxx)] connection timeout
[2015-10-27 21:47:47] System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Listener.AcceptCallback(IAsyncResult ar)

**Comment by dNEryno** [comment]
同,用auth那个插件就完全没速度了...感觉新出个插件 秒被封啊.

**Comment by breakwa11** [comment]
failed to recv data in handshakeReceive2Callback
这基本上是迅雷的锅
至于auth插件的客户端实现有bug，在修

**Comment by Balanky** [comment]
@breakwa11 从来都不装迅雷，并且Windows下都是裸奔呢

**Comment by breakwa11** [comment]
试试BT sync里的3.6.1.3版

**Comment by cfcboy** [comment]
@breakwa11 好像没用。感觉像是服务端出问题了。git pull之后的问题。

**Comment by robbielj** [comment]
应该是修复了，昨天服务器上pull了后同样错误只好撤掉，今天升级了客户端，服务器端也pull了没有问题

**Comment by cfcboy** [comment]
@robbielj 不知道怎么撤掉啊？哪个命令。

**Comment by robbielj** [comment]
@cfcboy  先git reflog 看HEAD历史记录，左边是hash值，然后git reset --hard hash值回退

不过现在应该是修复了吧你有重新pull一次么

**Comment by Balanky** [comment]
@breakwa11 @robbielj 升级客户端到3.6.1.3及再pull（没有新的更新）后还是不行，退回去可以了。感谢！

**Comment by breakwa11** [comment]
刚才修了几个问题，有空测测看，你们的服务端是不是没有IPv6地址？

**Comment by cfcboy** [comment]
@robbielj 感谢。你的方法是正确的。。已经恢复。

@breakwa11 就是服务端的问题。客户端OK。。。git pull恢复到之前的，一切就安静了。。请检查一下服务端源码。

**Comment by Balanky** [comment]
@breakwa11 是了，激活IPv6后最新版的可用了

**Comment by Balanky** [comment]
还有问题
[2015-10-29 09:33:30] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-10-29 09:33:30]  0 0 Void LogUsefulException(System.Exception)
 0 0 Void PipeConnectionReceiveCallback(System.IAsyncResult)
 0 0 Void Complete(IntPtr)
 0 0 Void CompleteCallback(System.Object)
 0 0 Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 0 0 Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 0 0 Void Complete(IntPtr)
 0 0 Void ProtectedInvokeCallback(System.Object, IntPtr)
 0 0 Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
 0 0 Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by brownursidaeR** [comment]
tumblr load图或者刷新都十分慢，和线路有关吗？

Balanky <notifications@github.com>于2015年10月29日周四 09:40写道：

**Comment by breakwa11** [comment]
@Balanky @brownursidaeR 新版本增加了一个ipv6的开关，表示是否优先使用v6地址，部分节点可能关了会快一些，试试 看

**Comment by cfcboy** [comment]
@breakwa11 现在已经不敢git pull了。感觉老版的，还是最快。

**Comment by breakwa11** [comment]
你可以开新目录git clone多开一个来测试

**Comment by cfcboy** [comment]
@breakwa11 感谢，已经测试。最新版的,git pull后没有问题。挺好用的。
