### ISSUE TITLE
咋回事？谢了System.ComponentModel.Win32Exception (0x80004005): 拒绝访问

### ISSUE THREAD

**Issue by zhangqiushide** [breakwa11/shadowsocks-rss#137]
[2015-11-15 16:38:11] System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
[2015-11-15 16:38:11] Void LogUsefulException(System.Exception)
Void Reload()
Void Main(System.String[])
3.6.3.2版本 谢了 问题出在哪呢

**Comment by breakwa11** [comment]
你把EXE文件放在什么目录下了？不要放桌面或C盘根目录或系统目录等，会导致privoxy无法运行

**Comment by zhangqiushide** [comment]
嗯 放在G盘非根目录下变成这样 咋回事呢 谢 没有google到该问题的解决办法呀
[2015-11-16 21:14:54] System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
[2015-11-16 21:14:54] Void LogUsefulException(System.Exception)
Void Reload()
Void Main(System.String[])

[2015-11-16 21:15:04] [Error]connect to update server error

**Comment by breakwa11** [comment]
这情况我也没见过，不知道是不是权限问题，你有没有安装什么安全软件或杀毒软件？或者你试试用管理员运行？两个exe都是一样的错误么？
也许你可以试试使用内置http代理来临时绕过这个问题，不过那功能还不完善，只在无法使用privoxy时使用的

**Comment by JeremyFxx** [comment]
问题解决了吗，我的问题和这一模一样。

**Comment by ding352** [comment]
我今天也遇到了这个问题，需要以管理员方式运行就可以了。

**Comment by Fegor** [comment]
我的也是，管理员运行就可以，开机自启动就会报错。

**Comment by yunkehe** [comment]
Yes
