### ISSUE TITLE
启动ss-manyuser报错

### ISSUE THREAD

**Issue by findix** [breakwa11/shadowsocks-rss#172]
```zsh
2015-12-10 05:21:07 ERROR    Traceback (most recent call last):
  File "/opt/shadowsocks/db_transfer.py", line 161, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/opt/shadowsocks/db_transfer.py", line 90, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 411, in _connect
    self._get_server_information()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 539, in _get_server_information
    self.server_charset = charset_by_id(self.server_language).name
  File "/usr/lib/python2.6/site-packages/cymysql/charset.py", line 19, in by_id
    return self._by_id[id]
KeyError: 224
```

看上去好像是数据库连接的问题，但是我确定数据库账号密码端口应该都是对的，和ss-panel设置一样，ss-panel 完全没问题

```
#Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'ss'
MYSQL_PASS = 'ss'
MYSQL_DB = 'shadowsocks'
MYSQL_TRANSFER_MUL = 1.0

MANAGE_PASS = 'ss233333333'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333
```

求解，谢谢大家！

**Comment by mikelei8291** [comment]
你的ss-panel和shadowsocks-rss是放在同一个服务器上运行的？

**Comment by findix** [comment]
是的

**Comment by mikelei8291** [comment]
没安装cymysql？
`pip install cymysql`

**Comment by findix** [comment]
不是的，如果是 module 问题 throw 的 Exception 不一样的

**Comment by mengzxh** [comment]
遇到同一个问题解决了吗？

**Comment by leehost** [comment]
kill ，重新开

**Comment by Sumzibuyu** [comment]
https://github.com/breakwa11/shadowsocks我在这里下载的，貌似是2.8 python服务端最新版哪里下载？？
