### ISSUE TITLE
python client 和privoxy的错误

### ISSUE THREAD

**Issue by antikan** [breakwa11/shadowsocks-rss#189]
ubuntu上运行python client，使用privoxy做http代理，出现大量如下错误：
 INFO     TCP connecting clients4.google.com:443 from 192.168.1.33:52527
ERROR    ord() expected string of length 1, but int found when handling connection from 192.168.1.33:52527

**Comment by breakwa11** [comment]
你加-v参数运行，再发一下log

**Comment by antikan** [comment]
还是这样的问题：
ERROR    ord() expected string of length 1, but int found when handling connection from 192.168.5.44:52552
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/tcprelay.py", line 466, in _handle_stage_addr
    head_len = self._get_head_size(data, 30)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/tcprelay.py", line 404, in _get_head_size
    head_type = ord(buf[0]) & 0xF
TypeError: ord() expected string of length 1, but int found

**Comment by breakwa11** [comment]
修好了，更新一下，看样子你用的是python3吧，有可能还有问题，如果可以的话帮忙再仔细测测看

**Comment by antikan** [comment]
还是不行，新问题：
                                  DEBUG    local_client_id b'a53536f0'
2015-12-28 20:06:05 ERROR    'int' does not support the buffer interface when handling connection from 192.168.5.44:52578
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/tcprelay.py", line 472, in _handle_stage_addr
    data_to_send = self._obfs.client_encode(data_to_send)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfs.py", line 68, in client_encode
    return self.obfs.client_encode(buf)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfsplugin/http_simple.py", line 98, in client_encode
    http_head = b"GET /" + self.encode_head(headdata) + b" HTTP/1.1\r\n"
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfsplugin/http_simple.py", line 82, in encode_head
    ret += '%' + binascii.hexlify(ch)
TypeError: 'int' does not support the buffer interface

**Comment by breakwa11** [comment]
好了，再试试

**Comment by antikan** [comment]
错误又变了：

ERROR    Can't convert 'bytes' object to str implicitly when handling connection from 192.168.5.44:52803
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/tcprelay.py", line 472, in _handle_stage_addr
    data_to_send = self._obfs.client_encode(data_to_send)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfs.py", line 68, in client_encode
    return self.obfs.client_encode(buf)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfsplugin/http_simple.py", line 98, in client_encode
    http_head = b"GET /" + self.encode_head(headdata) + b" HTTP/1.1\r\n"
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfsplugin/http_simple.py", line 82, in encode_head
    ret += '%' + binascii.hexlify(chr(ch))
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by breakwa11** [comment]
再试试看。。。。

**Comment by antikan** [comment]
ERROR    can't concat bytes to str when handling connection from 192.168.5.44:52965
 INFO     TCP connecting accounts.google.com:443 from 192.168.5.44:52966

**Comment by antikan** [comment]
这里有个类似的错误 TypeError: can't concat bytes to str, trying to use python3 http://stackoverflow.com/questions/25042212/typeerror-cant-concat-bytes-to-str-trying-to-use-python3?t=1451311502878

**Comment by antikan** [comment]
上面是不加-v运行，加上后的错误是：
ERROR    can't concat bytes to str when handling connection from 192.168.5.44:53130
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/tcprelay.py", line 472, in _handle_stage_addr
    data_to_send = self._obfs.client_encode(data_to_send)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfs.py", line 68, in client_encode
    return self.obfs.client_encode(buf)
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfsplugin/http_simple.py", line 99, in client_encode
    http_head += b"Host: " + (self.server_info.obfs_param or self.server_info.host) + port + b"\r\n"
TypeError: can't concat bytes to str
"/var/log/shadowsocks.log" 385L, 26581C

**Comment by breakwa11** [comment]
再试试看

**Comment by antikan** [comment]
晚上回来刚测试完，新版没问题了，多谢，辛苦了！
