### ISSUE TITLE
服务器运行报错

### ISSUE THREAD

**Issue by YiyangVVang** [breakwa11/shadowsocks-rss#193]
loaded collections.OrderedDict
IPv6 not support
INFO: loading config from shadowsocks.json
Traceback (most recent call last):
  File "server.py", line 191, in <module>
    main()
  File "server.py", line 38, in main
    config = shell.get_config(False)
  File "C:\shadowsocks\shadowsocks\../shadowsocks\shell.py", line 280, in get_co
nfig
    check_config(config, is_local)
  File "C:\shadowsocks\shadowsocks\../shadowsocks\shell.py", line 130, in check_
config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\shadowsocks\shadowsocks\../shadowsocks\encrypt.py", line 44, in try_c
ipher
    Encryptor(key, method)
  File "C:\shadowsocks\shadowsocks\../shadowsocks\encrypt.py", line 87, in __ini
t__
    random_string(self._method_info[1]))
  File "C:\shadowsocks\shadowsocks\../shadowsocks\encrypt.py", line 114, in get_
cipher
    return m[2](method, key, iv, op)
  File "C:\shadowsocks\shadowsocks\../shadowsocks\crypto\openssl.py", line 76, i
n __init__
    load_openssl()
  File "C:\shadowsocks\shadowsocks\../shadowsocks\crypto\openssl.py", line 39, i
n load_openssl
    'libcrypto')
  File "C:\shadowsocks\shadowsocks\../shadowsocks\crypto\util.py", line 83, in f
ind_library
    lib = CDLL(path)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by falseen** [comment]
python和openssl的位数必须跟系统一致，比如你系统是64位的，那python和openssl也必须是64位的。
