### ISSUE TITLE
Something is not working well.

### ISSUE THREAD

**Issue by ilikecola** [breakwa11/shadowsocks-rss#220]
Sometimes the upload connection is failed until timeout.And there is some logs in logfile.

[2016-01-22 21:47:47] ShadowsocksR started
[2016-01-22 22:01:30] System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at Shadowsocks.Obfs.TlsAuthObfs.ClientEncode(Byte[] encryptdata, Int32 datalength, Int32& outlength)
   at Shadowsocks.Controller.Handler.RemoteSend(Byte[] bytes, Int32 length)
   at Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2016-01-22 22:01:30] Void LogUsefulException(System.Exception)
Void PipeRemoteReceiveCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

Just repeat these message.
I use haproxy(v1.6) in Layer-4 mode to relay SS/Tcp connection.

SSR version 3.7.3.1
Encryption Chacha20
Protocol     auth_sha1
Obfs           tls1.0_session_auth

**Comment by breakwa11** [comment]
try set obfs="plain"

**Comment by ilikecola** [comment]
That means to disable obfs?

**Comment by breakwa11** [comment]
yes, I'm not sure what cause it, i worry about haproxy. try disable obfs makes haproxy just forward data

**Comment by ilikecola** [comment]
Once obfs disabled/"plain", log shows "ClientPostDecrypt ERROR", although it not disrupts the current connection.

**Comment by breakwa11** [comment]
is the new version working?

**Comment by ilikecola** [comment]
Work well.Thanks a lot.
