### ISSUE TITLE
为啥我就是访问不了youtube呢？全局也不可以

### ISSUE THREAD

**Issue by nonozone** [breakwa11/shadowsocks-rss#225]
访问提示：

```
The www.youtube.com page isn’t working

www.youtube.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

全局也不行。

同样的服务器我用SS，都没任何问题。

**Comment by breakwa11** [comment]
哪个版本的客户端？

**Comment by nonozone** [comment]
@breakwa11 就是最新版3.74的

**Comment by breakwa11** [comment]
开混淆或是别的什么配置呢？看起来像密码不对之类的强行断开

**Comment by nonozone** [comment]
@breakwa11 协议origin混淆plain，都是默认的。

**Comment by breakwa11** [comment]
服务端和客户端的log呢

**Comment by nonozone** [comment]
@breakwa11 刚把日志查看器清空，然后改成全局，然后刷新youtube，日志查看器那边没任何反应。

**Comment by nonozone** [comment]
```
[2016-01-28 15:44:42] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:33333
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.HttpPortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2016-01-28 15:44:42] Void LogUsefulException(System.Exception)
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

[2016-01-28 15:44:48] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:33333
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.HttpPortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2016-01-28 15:44:48] Void LogUsefulException(System.Exception)
Void ConnectCallback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

```
那个33333是哪里来的？

**Comment by nonozone** [comment]
发现我http://translate.google.com/ 也无法访问，但是Gplus又没问题... 没道理哎

**Comment by breakwa11** [comment]
33333不是你设置的本地端口么？

**Comment by nonozone** [comment]
@breakwa11 可是不管这个端口如何，我都全局了，为啥还是访问不了咧？

**Comment by breakwa11** [comment]
从你能访问G+来看，本身软件能工作，其它问题也许是你的配置导致的，如果你有更具体的描述要补充的话就reopen吧
