### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by iftrueme** [breakwa11/shadowsocks-rss#256]
INFO: loading config from user-config.json
2016-03-30 23:28:05 WARNING  warning: your timeout 15 seems too short
2016-03-30 23:28:05 INFO     loading libcrypto from libcrypto.so.10
Shadowsocks 
2016-03-30 23:28:05 INFO     db start server at port [23333] pass [zxyasa.1]
2016-03-30 23:28:05 INFO     starting server at [::]:23333
2016-03-30 23:28:05 WARNING  IPV6 [Errno 98] Address already in use 
2016-03-30 23:28:05 INFO     starting server at 0.0.0.0:23333
2016-03-30 23:28:05 WARNING  IPV4 [Errno 98] Address already in use 
2016-03-30 23:28:05 ERROR    [Errno 98] Address already in use
Traceback (most recent call last):
  File "/root/shadowsocks/server_pool.py", line 81, in _loop
    mgr.add_to_loop(loop)
  File "/root/shadowsocks/asyncmgr.py", line 56, in add_to_loop
    self._sock.bind((Config.MANAGE_BIND_IP, Config.MANAGE_PORT))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/root/shadowsocks/server_pool.py", line 44, in run
    ServerPool._loop(*self.params)
  File "/root/shadowsocks/server_pool.py", line 88, in _loop
    os.exit(0)
AttributeError: 'module' object has no attribute 'exit'

2016-03-30 23:28:20 INFO     db start server at port [23333] pass [zxyasa.1]
2016-03-30 23:28:20 INFO     starting server at [::]:23333
2016-03-30 23:28:20 WARNING  IPV6 [Errno 98] Address already in use 
2016-03-30 23:28:20 INFO     starting server at 0.0.0.0:23333
2016-03-30 23:28:20 WARNING  IPV4 [Errno 98] Address already in use

**Comment by iftrueme** [comment]
有时候错误会变成[Errno 104] Connection reset by peer 是什么原因导致的？已经关了防火墙

**Comment by iftrueme** [comment]
已经找到问题，shadowsocks3.0 windows客户端有关
