### ISSUE TITLE
用了一段时间提示数据库无法连接，重启后又可以了，好像并不是数据库问题

### ISSUE THREAD

**Issue by kuertianshi** [breakwa11/shadowsocks-rss#259]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/root/shadowsocksR/server_pool.py", line 44, in run
  File "/root/shadowsocksR/server_pool.py", line 83, in _loop
  File "/root/shadowsocksR/shadowsocks/eventloop.py", line 216, in run
  File "/root/shadowsocksR/shadowsocks/tcprelay.py", line 974, in handle_event
  File "/root/shadowsocksR/shadowsocks/tcprelay.py", line 112, in __init__
  File "/root/shadowsocksR/shadowsocks/encrypt.py", line 87, in __init__
  File "/root/shadowsocksR/shadowsocks/encrypt.py", line 37, in random_string
NotImplementedError: /dev/urandom not found

2016-04-04 00:46:21 ERROR    Traceback (most recent call last):
  File "/root/shadowsocksR/db_transfer.py", line 174, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocksR/db_transfer.py", line 76, in push_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '数据库地址' (-2)")

**Comment by breakwa11** [comment]
更新服务端，配置ulimit或直接使用脚本运行
