### ISSUE TITLE
配置了多用户版的pannel  然后 config.py 修改了host为另一个服务器的ip  其它的数据和panel的配置里的名称一样

### ISSUE THREAD

**Issue by jameseroyi** [breakwa11/shadowsocks-rss#300]
INFO: loading config from user-config.json
2016-05-23 09:24:24 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 185, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 31, in push_db_all_user
    curr_transfer = ServerPool.get_instance().get_servers_transfer()
  File "/root/shadowsocks/server_pool.py", line 72, in get_instance
    ServerPool.instance = ServerPool()
  File "/root/shadowsocks/server_pool.py", line 52, in __init__
    self.config = shell.get_config(False)
  File "/root/shadowsocks/shadowsocks/shell.py", line 289, in get_config
    check_config(config, is_local)
  File "/root/shadowsocks/shadowsocks/shell.py", line 130, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/shadowsocks/shadowsocks/encrypt.py", line 44, in try_cipher
    Encryptor(key, method)
  File "/root/shadowsocks/shadowsocks/encrypt.py", line 87, in __init__
    random_string(self._method_info[1]))
  File "/root/shadowsocks/shadowsocks/encrypt.py", line 114, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/shadowsocks/shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/root/shadowsocks/shadowsocks/crypto/sodium.py", line 40, in load_libsodium
    'libsodium')
  File "/root/shadowsocks/shadowsocks/crypto/util.py", line 83, in find_library
    lib = CDLL(path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libsodium.so.18: cannot open shared object file: No such file or directory

**Comment by breakwa11** [comment]
你配置的chacha20不支持，你未配置好libsodium
