### ISSUE TITLE
安装好重启后提示：No module named cymysql

### ISSUE THREAD

**Issue by impig33** [breakwa11/shadowsocks-rss#336]
python server.py -d start
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-07-15 18:03:20 INFO     util.py:85 loading libcrypto from libcrypto.so.6
Shadowsocks
2016-07-15 18:03:20 INFO     asyncdns.py:324 dns server: [('74.207.241.5', 53), ('74.207.242.5', 53), ('45.33.58.84', 53
)]
2016-07-15 18:03:20 ERROR    db_transfer.py:218 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 212, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 78, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 23, in update_all_user
    import cymysql
ImportError: No module named cymysql

配置好后已经可以使用了，于是重启一下，发现没有启动，手工启动就提示这个。

求解。

.

**Comment by breakwa11** [comment]
安装一下cymysql

**Comment by bearcolin** [comment]
装了 cymysql 之后，想停止一下，说这个：
2017-04-11 18:25:52 ERROR    db_transfer.py:260 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 242, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 377, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on u'127.0.0.1' (111)")

**Comment by QianCheng40** [comment]
+1, 请问有解决方案了吗？

**Comment by cyrilkong** [comment]
+1, 请问有解决方案了吗？
