### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by chenjl8** [breakwa11/shadowsocks-rss#339]
Debian 7 64位，后台运行run.sh 正常，iptables 规则都清除了，就是无法连上服务器，错误日志：

[2016-07-19 13:35:36] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 x.x.x.x:9050
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
能够正常连接前端ss-panel。

ss服务器后台运行信息：
2016-07-19 14:23:21 INFO     starting server at [::]:10001
2016-07-19 14:23:21 INFO     starting server at 0.0.0.0:10001
INFO: loading config from user-config.json
2016-07-19 14:52:21 INFO     loading libsodium from libsodium.so.18
2016-07-19 14:52:21 INFO     db start server at port [20000] pass [chen0002]
2016-07-19 14:52:21 INFO     starting server at [::]:20000
2016-07-19 14:52:21 INFO     starting server at 0.0.0.0:20000
2016-07-19 14:52:21 INFO     db start server at port [10001] pass [chen0002]
2016-07-19 14:52:21 INFO     starting server at [::]:10001
2016-07-19 14:52:21 INFO     starting server at 0.0.0.0:10001

redis     2588     1  0 Jul14 ?        00:06:49 /usr/bin/redis-server 127.0.0.1:6379       
root      2653     1  0 Jul14 ?        00:00:00 /serverspeeder/bin/acce-3.10.61.0-[Debian_7_3.2.0-4-amd64] -n 1 -s /serverspeeder/etc/apx-20341231.lic -m -p 256
root     27853     1  0 14:17 ?        00:00:00 /usr/local/bin/ss-server -c /etc/shadowsocks.json
root     28625     1  0 14:52 ?        00:00:01 python server.py m
root     28816 28802  0 15:13 pts/0    00:00:00 grep server

**Comment by breakwa11** [comment]
9050？你确定没有配置错误？

**Comment by chenjl8** [comment]
9050  端口，我单独使用ss-server测试过，没有问题的。配置完全按照指导配置，以下是配置文件，看不出哪里错了呀。
 后台监听无9050端口。登录ss-panel 没有问题的，就是连不上服务器。
config.json:
"server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 9050,
    "local_address": "127.0.0.1",
    "local_port": 20000,
    "password": "chen0002",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "chacha20",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false,
    "workers": 1
Config.py:
#Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'sspanel'
MYSQL_PASS = 'Chen1978#'
MYSQL_DB = 'sspanel'
MYSQL_TRANSFER_MUL = 1.0
MYSQL_UPDATE_TIME = 60

MANAGE_PASS = 'ss233333333'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333

**Comment by breakwa11** [comment]
你既然设置了数据库，那么端口是数据库决定的，你本地配置的端口没有用

**Comment by chenjl8** [comment]
你好

ss-panel 上设的端口是20000，shadowsocks
客户端设的也是20000，你的意思是说服务器本地端口不用设了吗？但不论用那个端口，都应该能连上才对。

2016-07-20 11:42 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by breakwa11** [comment]
那端口为20000的时候的log呢？

**Comment by chenjl8** [comment]
你好

在shadowsocks 客户端的就是问题抬头那个描述，不过不停的重复。

[2016-07-19 13:35:36] System.Net.Sockets.SocketException (0x80004005):
由于目标计算机积极拒绝，无法连接。 x.x.x.x:9050
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

2016-07-20 12:48 GMT+08:00 破娃酱 <notifications@github.com>:

**Comment by breakwa11** [comment]
你说设置了端口为20000，那你客户端为何还连接的9050

**Comment by chenjl8** [comment]
明白了，是ss-panel端口设置错了。测试后已经可以连上了，感谢

2016-07-20 13:15 GMT+08:00 破娃酱 <notifications@github.com>:
