### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MYSQL_SSL_ENABLE'

### ISSUE THREAD

**Issue by PioneerCloud** [breakwa11/shadowsocks-rss#340]
[root@iZ212sd~]# tail -f /var/log/ssserver.log
INFO: loading config from user-config.json
2016-07-20 19:27:25 INFO     util.py:85 loading libsodium from libsodium.so.18
2016-07-20 19:27:26 INFO     asyncdns.py:324 dns server: [('100.100.2.138', 53), ('100.100.2.136', 53)]
2016-07-20 19:27:26 ERROR    db_transfer.py:260 Traceback (most recent call last):
  File "/usr/sys/shadowsocks/db_transfer.py", line 255, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/usr/sys/shadowsocks/db_transfer.py", line 116, in pull_db_all_user
    if get_config().MYSQL_SSL_ENABLE == 1:
AttributeError: 'module' object has no attribute 'MYSQL_SSL_ENABLE'

阿里云Centos6.5 64bit 运行时候报错。
求助一下这个怎么办呢

**Comment by PioneerCloud** [comment]
试了一下刚刚不只是阿里云，很多服务器包括之前正常搭建过的。。现在都是这个报错

**Comment by glzjin** [comment]
userapiconfig.py 添加配置项 MYSQL_SSL_ENABLE=0
