### ISSUE TITLE
多用户版无法运行，apiconfig.py这个文件clone下来的时候就是有问题的，是不是放错了？

### ISSUE THREAD

**Issue by kkbbzjh** [breakwa11/shadowsocks-rss#344]
python server.py
之后显示：
loaded collections.OrderedDict
IPv6 support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "server.py", line 38, in run
    self.obj.thread_db(self.obj)
  File "/root/shadowsocks/db_transfer.py", line 174, in thread_db
    db_instance = obj()
  File "/root/shadowsocks/db_transfer.py", line 216, in __init__
    self.load_cfg()
  File "/root/shadowsocks/db_transfer.py", line 220, in load_cfg
    config_path = get_config().MYSQL_CONFIG
AttributeError: 'module' object has no attribute 'MYSQL_CONFIG'

之前安装的时候都没有问题，是不是文件放错了？我把另外一个服务器的文件复制过来都不行

**Comment by SnakeMa** [comment]
我的错误和你类似：
File "/root/shadowsocks/db_transfer.py", line 174, in thread_db
    db_instance = obj()
  File "/root/shadowsocks/db_transfer.py", line 216, in __init__
    self.load_cfg()
  File "/root/shadowsocks/db_transfer.py", line 222, in load_cfg
    with open(config_path, 'r+') as f:
IOError: [Errno 2] No such file or directory: 'usermysql.json'

loaded collections.OrderedDict
IPv6 support

**Comment by wenliyang** [comment]
ssr-python服务端更新，注意，本次更新配置方式有变化，
这里从git clone后开始说明：

首先cp apiconfig.py userapiconfig.py
如果你用的是单用户或mudbjson模式，就保持不变，可忽略下文
如果你用的是数据库模式，那么修改userapiconfig.py中的API_INTERFACE，接着继续执行：
cp mysql.json usermysql.json
最后数据库的所有参数在usermysql.json里修改，保存重启即可。

简单的说，即原本在userapiconfig.py里面的数据库配置，移动到usermysql.json里面

以上内容取自：
https://telegram.me/shadowsocksr

**Comment by kkbbzjh** [comment]
谢谢！
