### ISSUE TITLE
【求助】一直 Connection reset by peer

### ISSUE THREAD

**Issue by LiYisen** [breakwa11/shadowsocks-rss#365]
确认密码端口混淆协议均无问题，
事实上我的VPS上还运行着ocserv，使用正常。
这个情况持续2天了，实在解决不了了。
客户端开启代理后，开始科学上网，服务端一直循环打下面两行日志
2016-08-04 10:22:52 ERROR    tcprelay.py:842 exception from ::ffff:183.39.157.27:58631
2016-08-04 10:22:52 ERROR    tcprelay.py:841 [Errno 104] Connection reset by peer
客户端日志如下
[2016-08-04 21:54:04] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadPACCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-08-04 21:54:04] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadPACCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
System.Object UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
System.Object UnsafeInvoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

几个小时前还会打下面三种日志
tcprelay.py:888 can not parse header when handling connection from
common.py:228 unsupported addrtype 211, maybe wrong password or encryption method
tcprelay.py:383 Protocol ERROR, TCP ogn data 16030100520100004e030157a3460b6513dac479b06be91fce96ca7f4aebbd84e748ce6300a87256901f3200002600390038003500160013000a00330032002f0005000400150012000900140011000800060003020100
有遇到这个问题的同学交流一下呗。

**Comment by LiYisen** [comment]
今天试了还是一样，有人遇到一样的情况吗？

**Comment by breakwa11** [comment]
原因不清楚，如果只有Connection reset by peer，那么应该是你的服务器被干扰，考虑换IP吧

**Comment by LiYisen** [comment]
嗯，只好换ip再试试了，今天看了确实只有Connection reset by peer。晚上换完再回来汇报下情况

**Comment by LiYisen** [comment]
换了IP也不行，上来就直接Connection reset by peer。可能是公司网络出口做了限制？回家再试试。。。

**Comment by Enoemoston** [comment]
不知道我的问题和楼主是否类似 ~

2016-08-07 08:52:00 ERROR    tcprelay.py:850 when connect to 104.45.231.79:443
2016-08-07 08:52:27 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:52:27 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:52:27 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:52:27 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:53:30 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:53:30 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:53:30 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:53:30 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:54:55 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:54:55 ERROR    tcprelay.py:850 when connect to 8.7.198.45:443
2016-08-07 08:54:59 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:54:59 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:56:00 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:56:00 ERROR    tcprelay.py:850 when connect to 8.7.198.45:443
2016-08-07 08:56:02 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:56:02 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:56:24 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:56:24 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:57:28 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:57:28 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:58:32 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 08:58:32 ERROR    tcprelay.py:850 when connect to 37.61.54.158:443
2016-08-07 08:58:44 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 08:58:44 ERROR    tcprelay.py:850 when connect to 40.96.1.210:443
2016-08-07 09:00:53 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:00:53 ERROR    tcprelay.py:850 when connect to 202.89.233.104:443
2016-08-07 09:02:30 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:02:30 ERROR    tcprelay.py:850 when connect to 202.89.233.104:443
2016-08-07 09:12:00 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:12:00 ERROR    tcprelay.py:850 when connect to 202.89.233.104:443
2016-08-07 09:14:16 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:14:16 ERROR    tcprelay.py:850 when connect to 202.89.233.103:443
2016-08-07 09:14:18 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:14:18 ERROR    tcprelay.py:850 when connect to 202.89.233.103:443
2016-08-07 09:16:49 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 09:16:49 ERROR    tcprelay.py:850 when connect to 8.7.198.45:443
2016-08-07 09:17:52 ERROR    tcprelay.py:848 [Errno 110] Connection timed out
2016-08-07 09:17:52 ERROR    tcprelay.py:850 when connect to 8.7.198.45:443
2016-08-07 09:21:54 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:21:54 ERROR    tcprelay.py:850 when connect to 168.63.242.221:443
2016-08-07 09:22:26 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:22:26 ERROR    tcprelay.py:850 when connect to 104.45.231.79:443
2016-08-07 09:22:26 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer
2016-08-07 09:22:26 ERROR    tcprelay.py:850 when connect to 104.45.231.79:443
2016-08-07 08:44:37 INFO     server.py:134 starting server at 103.192.177.125:80
2016-08-07 08:52:00 ERROR    tcprelay.py:848 [Errno 104] Connection reset by peer

Win 10 客户端倒是没问题，使用路由器版客户端无法使用，无论我如何配置 DNS 污染解决不了，以上是服务器的报错 ~

**Comment by LiYisen** [comment]
我也觉得奇怪。不过你的日志里面打了很多timeout，你ping下你的ip看看丢包多不多。
我的是直接reset，但是我发现我在家里能用，在公司不能。
事实上有同事也在用，又能用。目前原因不明。明天去公司之后我再查一查。
不懂python，看来要学学

**Comment by Enoemoston** [comment]
我 ping 的延迟一直很低，100+，本来就是香港线路vps，速度还可以~

**Comment by LiYisen** [comment]
在公司的时候，服务端日志是这样的
2016-08-08 02:29:21 INFO     connecting api.github.com:443 from 183.39.159.69:50415
2016-08-08 02:29:22 ERROR    [Errno 104] Connection reset by peer
2016-08-08 02:29:36 ERROR    [Errno 104] Connection reset by peer
2016-08-08 02:30:04 INFO     connecting www.google.com:443 from 183.39.159.69:50430
2016-08-08 02:30:05 ERROR    [Errno 104] Connection reset by peer
2016-08-08 02:30:10 INFO     connecting www.google.com:443 from 183.39.159.69:50434
2016-08-08 02:30:13 ERROR    [Errno 104] Connection reset by peer
2016-08-08 02:30:13 INFO     connecting www.google.com:443 from 183.39.159.69:50440
2016-08-08 02:30:14 ERROR    [Errno 104] Connection reset by peer

不过昨天在家可以正常用。

**Comment by LiYisen** [comment]
今天在公司抓包看了。只要访问Google，客户端和服务端都会立刻受到reset包。应该是ip被盯上了。现在回到家里又能上，应该是出口不同吧。毕竟在公司别的同事又能用，我也是醉了。
这个issues应该可以关了。
然后楼上的情况是一堆timeout，跟我这个应该不是同一个原因吧。

**Comment by lingaoyi** [comment]
原装SS出现马上断开，跟作者反应过，作者让我提高超时，但没效果的，用上了SSR加了混淆和协议之后就算出现也不会断开了。

**Comment by LiYisen** [comment]
我这里原因问到了，公司的防火墙搞的鬼，难怪家里能上公司不能上。同事能上是因为他用了另一个上网环境

**Comment by wangweichang** [comment]
楼主你好，我也遇到一样的问题。请问最后你是怎么解决的？谢谢！

**Comment by letxxt** [comment]
能上网，就是日志不停显示这些
