### ISSUE TITLE
多节点一启动 错误！

### ISSUE THREAD

**Issue by sunyh87** [breakwa11/shadowsocks-rss#366]
ERROR:root:Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 184, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 296, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 433, in pull_db_users
    cur.execute("SELECT " + ','.join(keys) + " FROM user")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'obfs_param' in 'field list'")

**Comment by sunyh87** [comment]
这是啥原因啊，求指导

**Comment by breakwa11** [comment]
不要配置为你的数据库不支持的API_INTERFACE
