### ISSUE TITLE
这个是啥问题?

### ISSUE THREAD

**Issue by hzh1990** [breakwa11/shadowsocks-rss#380]
[root@hzh shadowsocks]# ./logrun.sh
[root@hzh shadowsocks]# ./tail.sh
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.7/site-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.7/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.7/site-packages/cymysql/err.py", line 135, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
OperationalError: (1045, u"Access denied for user 'ss'@'127.0.0.1' (using password: YES)")

2016-08-14 02:07:48 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-08-14 02:07:48 INFO     asyncdns.py:324 dns server: [('108.61.xx.xx', 53)]
2016-08-14 02:07:48 ERROR    db_transfer.py:191 Traceback (most recent call last):
  File "/usr/local/shadowsocks/db_transfer.py", line 184, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/usr/local/shadowsocks/db_transfer.py", line 294, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.7/site-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.7/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.7/site-packages/cymysql/err.py", line 135, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
OperationalError: (1045, u"Access denied for user 'ss'@'127.0.0.1' (using password: YES)")

**Comment by breakwa11** [comment]
你的数据库用户拒绝访问
