### ISSUE TITLE
3.8.4.1e以后的都不能用 日志如下

### ISSUE THREAD

**Issue by zhuguang0925** [breakwa11/shadowsocks-rss#390]
[2016-08-19 18:08:36] ShadowsocksR started
[2016-08-19 18:08:43] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-08-19 18:08:43] Void LogUsefulException(System.Exception)
Void controller_UpdatePACFromGFWListError(System.Object, System.IO.ErrorEventArgs)
Void pacServer_PACUpdateError(System.Object, System.IO.ErrorEventArgs)
Void http_DownloadGFWTemplateCompleted(System.Object, System.Net.DownloadStringCompletedEventArgs)
Void OnDownloadStringCompleted(System.Net.DownloadStringCompletedEventArgs)
Void DownloadStringOperationCompleted(System.Object)
System.Object _InvokeMethodFast(System.IRuntimeMethodInfo, System.Object, System.Object[], System.SignatureStruct ByRef, System.Reflection.MethodAttributes, System.RuntimeType)
System.Object InvokeMethodFast(System.IRuntimeMethodInfo, System.Object, System.Object[], System.Signature, System.Reflection.MethodAttributes, System.RuntimeType)
System.Object Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, Boolean)
System.Object DynamicInvokeImpl(System.Object[])
Void InvokeMarshaledCallbackDo(ThreadMethodEntry)
Void InvokeMarshaledCallbackHelper(System.Object)
Void runTryCode(System.Object)
Void ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void InvokeMarshaledCallback(ThreadMethodEntry)
Void InvokeMarshaledCallbacks()
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-08-19 18:08:45] [Error]connect to update server error
[2016-08-19 18:28:05] ShadowsocksR started
[2016-08-19 18:28:14] [Error]connect to update server error

**Comment by breakwa11** [comment]
麻烦发issue除了给出log，还请给出服务器统计界面的截图，及服务器log，你这问题多半都是配置不正确，自己检查清楚啊

**Comment by goxofy** [comment]
你们3.8+的版本都是从哪里下载的啊，github上release页面只有3.7啊

**Comment by uloveme** [comment]
我也很好奇，现在用的3.8.4.2，忘记哪里下载的了

**Comment by q54528** [comment]
bit torrent sync

**Comment by q54528** [comment]
sync 里面只到3.8.3，你们的3.8.4哪里搞的

**Comment by yichengchen** [comment]
现在都是在zeronet下的…
