### ISSUE TITLE
SSL连接mysql db 错误

### ISSUE THREAD

**Issue by wewe5dfbb** [breakwa11/shadowsocks-rss#418]
mysql db在远程的服务器10.0.0.23，本地地址10.0.0.22. usermysql.json中ssl_enable = 0 是可以正常连接的。设置为1就报如下错误

```
root@sserver2:/usr/local/shadowsocks# python server.py 
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-09-01 20:42:41 WARNING  shell.py:117 warning: your timeout 60 seems too short
2016-09-01 20:42:41 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
Shadowsocks 
2016-09-01 20:42:41 INFO     asyncdns.py:324 dns server: [('75.75.75.75', 53), ('75.75.76.76', 53)]
2016-09-01 20:42:41 INFO     db_transfer.py:194 current process RLIMIT_NOFILE resource: soft 51200 hard 51200
2016-09-01 20:42:41 ERROR    db_transfer.py:208 Traceback (most recent call last):
  File "/usr/local/shadowsocks/db_transfer.py", line 201, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/usr/local/shadowsocks/db_transfer.py", line 309, in pull_db_all_user
    ssl={'ca':self.cfg["ssl_enable"],'cert':self.cfg["ssl_enable"],'key':self.cfg["ssl_enable"]})
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 472, in _send_authentication
    ca_certs=self.ca)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_verify_locations(ca_certs)
TypeError: coercing to Unicode: need string or buffer, int found

```
配置文件如下

```
root@sserver2:/usr/local/shadowsocks# cat usermysql.json
{
    "host": "10.0.0.23",
    "port": 1111,
    "user": "dbadmin",
    "password": "xx",
    "db": "shadowsocks",
    "node_id": 2,
    "transfer_mul": 1.0,
    "ssl_enable": 1,
    "ssl_ca": "/usr/local/shadowsocks/certs/ca.pem",
    "ssl_cert": "/usr/local/shadowsocks/certs/client-cert.pem",
    "ssl_key": "/usr/local/shadowsocks/certs/client-key.pem"
}
```

用MySQLdb模块测试没有问题
```
root@sserver2:~# python mysqldb.py 
(u'Ssl_cipher', u'DHE-RSA-AES256-SHA')
```

测试脚本
```
root@sserver2:~# cat mysqldb.py 
#!/usr/bin/env python
import MySQLdb
ssl = {'cert': '/usr/local/shadowsocks/certs/client-cert.pem', 'key': '/usr/local/shadowsocks/certs/client-key.pem'}
conn = MySQLdb.connect(host='10.0.0.23', port=1111, user='dbadmin', passwd='xx', db='shadowsocks', charset='utf8',ssl=ssl)
cursor = conn.cursor()
cursor.execute('SHOW STATUS like "Ssl_cipher"')
print cursor.fetchone()
```

mysql直接连接也没有问题，SSL工作应该是正常的
```
root@sserver2:/usr/local/shadowsocks/certs#  mysql -u dbadmin -p --ssl-ca=ca.pem --ssl-cert=client-cert.pem --ssl-key=client-key.pem -h 10.0.0.23 -P 1111
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 383
Server version: 5.7.13-0ubuntu0.16.04.2 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> status
--------------
mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper

Connection id:          383
Current database:
Current user:           dbadmin@10.0.0.22
SSL:                    Cipher in use is DHE-RSA-AES256-SHA
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.13-0ubuntu0.16.04.2 (Ubuntu)
Protocol version:       10
Connection:             10.0.0.23 via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:               1111
Uptime:                 2 hours 12 min 36 sec

Threads: 1  Questions: 1791  Slow queries: 0  Opens: 183  Flush tables: 1  Open tables: 98  Queries per second avg: 0.225
--------------
```

总感觉是那个函数pass argument出问题了。麻烦帮忙解决，谢谢。

**Comment by wewe5dfbb** [comment]
找到问题了
db_transfer.py中所有
ssl={'ca':self.cfg["ssl_enable"],'cert':self.cfg["ssl_enable"],'key':self.cfg["ssl_enable"]})
改为
ssl={'ca':self.cfg["ssl_ca"],'cert':self.cfg["ssl_cert"],'key':self.cfg["ssl_key"]})

**Comment by breakwa11** [comment]
好的，我更新一下代码

**Comment by wewe5dfbb** [comment]
Thanks.
