### ISSUE TITLE
多用户版，远程机器连不上数据库，报错。

### ISSUE THREAD

**Issue by hzjixiang** [breakwa11/shadowsocks-rss#445]
错误代码
2016-09-17 02:20:05 ERROR    db_transfer.py:208 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 201, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 313, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on u'138.128.209.**' (110)")

和他一样https://github.com/breakwa11/shadowsocks-rss/issues/10

换过V2版本试过，也是同样报错。

**Comment by breakwa11** [comment]
检查ip和防火墙

**Comment by hzjixiang** [comment]
谢谢 已解决

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
@hzjixiang 怎么解决的?

**Comment by hzjixiang** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls   服务端 新建立个账户，开启远程访问权限，root账号我一直试了不行。 具体你看我这个帖子http://bbs.vpser.net/thread-14467-1-1.html
