### ISSUE TITLE
 shell.py:50 [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by didila** [breakwa11/shadowsocks-rss#469]
因為我每天都會git更新服務端的文件
而今天卻發現
我有好幾台服務器今天都出現大量的 shell.py:50 [Errno 11] Resource temporarily unavailable
然後客户端連線後無法瀏覽內容
昨天之前並沒有這些問題
我的服务器为ubuntu 14.04 KVM 512MB
只有运行SSR

**Comment by breakwa11** [comment]
目前没有其它人反馈相同问题，暂时不清楚原因。你可以试试修改dns看看有没有改善，另外程序重启能解决这个问题吗

**Comment by didila** [comment]
重启后会恢复，但是不用多久又开始出现很多的Resource temporarily unavailable

**Comment by breakwa11** [comment]
@didila 你需要按wiki的ulimit页面修改一下配置，看看服务端启动时的log，关于nofile limit的，发来看看我确认一下

**Comment by didila** [comment]
服务端启动时的log很正常，就開始連線使用就出現了。
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3852
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 51200
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3852
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by didila** [comment]
fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 65536
net.core.wmem_default = 65536
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_congestion_control = hybla
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
vm.swappiness=10

**Comment by breakwa11** [comment]
关键的地方我再重复一次，看看服务端启动时的log，关于nofile limit的，发来看看我确认一下

**Comment by didila** [comment]
> ulimit -Hn
51200

> cat /etc/security/limits.conf
* soft nofile 51200
* hard nofile 1024000

服務端重啟的log
> cat shadowsocks.log
2016-10-07 17:12:37 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('4.2.2.1', 53), ('209.244.0.3', 53), ('208.67.222.222', 53)]
2016-10-07 17:12:37 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [xxxxxx] method [chacha20-ietf] obfs [tls1.2_ticket_auth] obfs_param [0]
2016-10-07 17:12:37 INFO     server.py:134 starting server at 0.0.0.0:1458
2016-10-07 17:12:37 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [xxxxxx] method [chacha20-ietf] obfs [tls1.2_ticket_auth] obfs_param [0]
2016-10-07 17:12:37 INFO     server.py:134 starting server at 0.0.0.0:1459
2016-10-07 17:12:37 INFO     server.py:98 server start with protocol[auth_sha1_v2] password [xxxxxx] method [chacha20-ietf] obfs [tls1.2_ticket_auth] obfs_param [0]
2016-10-07 17:12:37 INFO     server.py:134 starting server at 0.0.0.0:1221
2016-10-07 17:12:37 INFO     server.py:171 worker started
2016-10-07 17:12:37 INFO     server.py:171 worker started
2016-10-07 17:12:37 INFO     server.py:171 worker started
2016-10-07 17:12:44 ERROR    tcprelay.py:836 [Errno 111] Connection refused

**Comment by breakwa11** [comment]
@didila log里显示你的服务端是旧的，并没有包含我所说的log

**Comment by didila** [comment]
难道不能将shadowsocks子目录单独抽出来用？因为我每天都有git更新manyuser版，然后下载后将子目录抽出来用。
你上次也说过我的服务端是旧的我就纳闷了...

**Comment by breakwa11** [comment]
@didila 我怀疑你使用了一键包安装

**Comment by didila** [comment]
不，我自己写的安装脚本，是参考wiki自己写的，我不清楚外面的一键安装是什么内容

**Comment by breakwa11** [comment]
@didila 但你的版本确实是旧的，请更新

**Comment by didila** [comment]
那我确认一下，这个git方式没错吧？
git clone -b manyuser https://github.com/breakwa11/shadowsocks.git

**Comment by breakwa11** [comment]
@didila 对的

**Comment by didila** [comment]
好的，谢谢，我再试试

**Comment by jillojill** [comment]
能写shadowsocks 得是什么程度？？


Sent from my Samsung device

-------- Original message --------

**Comment by didila** [comment]
因为Resource temporarily unavailable实在找不到问题点，我用了debug log生成以下内容
貌似是udp转发惹的祸，我的主机可以用udp

2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1114 accept
2016-11-02 07:48:15 ERROR    shell.py:50 [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
2016-11-02 07:48:15 DEBUG    tcprelay.py:1014 server port   231 connections = 4
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1379, in handle_event
    self._handle_server()
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/udprelay.py", line 1035, in _handle_server
    data, r_addr = server.recvfrom(BUF_SIZE)
error: [Errno 11] Resource temporarily unavailable
