### ISSUE TITLE
请问这个是什么原因，搭建SS后端给WHMCS使用

### ISSUE THREAD

**Issue by ilovebamboo** [breakwa11/shadowsocks-rss#498]
[root@host-150-95-136-25 shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-10-23 21:35:36 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-10-23 21:35:36 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]
2016-10-23 21:35:36 INFO     shell.py:80 ShadowsocksR 2.9.6 2016-10-17
2016-10-23 21:35:36 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2016-10-23 21:35:36 WARNING  db_transfer.py:536 no user in json file
2016-10-23 21:36:36 WARNING  db_transfer.py:536 no user in json file

**Comment by breakwa11** [comment]
@ilovebamboo 配置错误，请检查配置

**Comment by ilovebamboo** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup(manyuser-with-mysql)
我是按照这个配置的
谢谢，请问是那个配置啊 有问题啊？

user-config.json
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "m",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "rc4-md5",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "tls1.0_session_auth_compatible",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}

userapiconfig.py
-----

# Config
API_INTERFACE = 'mudbjson' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)
UPDATE_TIME = 60
SERVER_PUB_ADDR = '127.0.0.1' # mujson_mgr need this to generate ssr link

#mudb
MUDB_FILE = 'mudb.json'

# Mysql
MYSQL_CONFIG = 'usermysql.json'

# API
MUAPI_CONFIG = 'usermuapi.json'

----
usermysql.json
{
    "host": "xxx.xxx.com",
    "port": 3306,
    "user": "blackrose",
    "password": "blackrose",
    "db": "shadowsocks",
    "node_id": 0,
    "transfer_mul": 1.0,
    "ssl_enable": 0,
    "ssl_ca": "",
    "ssl_cert": "",
    "ssl_key": ""
}

**Comment by breakwa11** [comment]
@ilovebamboo 你作为后端就不应该 API INTERFACE = 'mudbjson' ，请看文档

**Comment by ilovebamboo** [comment]
我把 API INTERFACE = 'sspanelv3' 就变成这样了。


[root@host-150-95-136-25 shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-10-23 22:24:28 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-10-23 22:24:28 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]
2016-10-23 22:24:28 INFO     shell.py:80 ShadowsocksR 2.9.6 2016-10-17
2016-10-23 22:24:28 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2016-10-23 22:24:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:25:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:26:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:27:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:28:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:29:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:30:28 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:31:31 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:32:31 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:33:31 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:34:31 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

2016-10-23 22:35:31 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 324, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 447, in pull_db_users
    cur.execute("SELECT " + ','.join(node_info_keys) +" FROM ss_node where `id`='" + str(self.cfg["node_id"]) + "'")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")

**Comment by breakwa11** [comment]
我再说一次，看文档，你这还是配置错误，再这样下去除了变成一步一步改你的配置就没别的了

**Comment by ilovebamboo** [comment]
不好意思，打搅您宝贵的时间了。我是看文档一步一步操作的。

**Comment by breakwa11** [comment]
那你总应该看得懂这句吧
```
ProgrammingError: (1146, u"Table 'shadowsocks.ss_node' doesn't exist")
```

**Comment by ilovebamboo** [comment]
好像是数据库不匹配吗

**Comment by ilovebamboo** [comment]
不知道什么原因。
