### ISSUE TITLE
shadowsocks在centos上安装失败的原因到底如何解决

### ISSUE THREAD

**Issue by ziluopao** [breakwa11/shadowsocks-rss#586]
https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup(manyuser-with-mysql)
我是根据上面的方法安装的，其中到了这一步**python server.py**出现了错误，提示如下
[root@vpn114 shadowsocks]# python server.py
IPv6 support
INFO: loading config from user-config.json
/root/shadowsocks/shadowsocks/shell.py:177: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message)
ERROR: found an error in config.json: Expecting : delimiter: line 2 column 13 (char 14)
[root@vpn114 shadowsocks]# 
我用的是centos6.4 64位的版本。
不知这种情况如何解决呢

**Comment by ziluopao** [comment]
这是我的配置文件,这样写不知哪里需要改。
[root@vpn114 shadowsocks]# vi user-config.json 

{
    "server"0.0.0.0":
    "server_ipv6": "::",
    "server_port": 5555,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "adbdd",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "aes-256-cfb",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "tls1.0_session_auth_compatible",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}

**Comment by breakwa11** [comment]
@ziluopao 第二行server后面格式就错了，而且你写的这混淆和协议已经过时，不支持

**Comment by ziluopao** [comment]
你是说"server"0.0.0.0":这个难道改成我的IP？

**Comment by breakwa11** [comment]
@ziluopao 格式错误，请看清楚

**Comment by ziluopao** [comment]
改正后有所成效
提示如下
[root@vpn114 shadowsocks]# python server.py
IPv6 support
INFO: loading config from user-config.json
2016-12-29 00:41:57 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-12-29 00:41:57 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-12-29 00:41:57 INFO     shell.py:80 ShadowsocksR 3.0.0 2016-12-23
2016-12-29 00:41:57 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2016-12-29 00:41:57 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 336, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocks/db_transfer.py", line 352, in pull_db_users
    cur.execute("SELECT " + ','.join(keys) + " FROM user")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'vpn114.user' doesn't exist")
但还是有错误，我不知道**ProgrammingError: (1146, u"Table 'vpn114.user' doesn't exist"**指的什么

**Comment by ziluopao** [comment]
确实是表导入错了，改过来了，不过再运行又有新的警告了，提示如下：
[root@vpn114 shadowsocks]# python server.py
IPv6 support
INFO: loading config from user-config.json
2016-12-29 00:56:45 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-12-29 00:56:45 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-12-29 00:56:45 INFO     shell.py:80 ShadowsocksR 3.0.0 2016-12-23
2016-12-29 00:56:45 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2016-12-29 00:56:45 WARNING  db_transfer.py:341 no user in db

**Comment by guliujian** [comment]
为什么就不能认真看一下报错呢，上面写的很简洁明了啊，no user in db 翻译为数据库中没有用户

**Comment by ziluopao** [comment]
呵呵，不好意思，我突然明白了，我正从小小白向小白过渡，见笑了！
