### ISSUE TITLE
用命令行启动报错

### ISSUE THREAD

**Issue by nickeyfff** [breakwa11/shadowsocks-rss#617]
python server.py  -p 9388 -k 123123123  -m aes-256-cfb                
loaded collections.OrderedDict
IPv6 support
2017-01-07 17:09:44 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2017-01-07 17:09:44 INFO     shell.py:80 ShadowsocksR 3.0.0 2016-12-23
2017-01-07 17:09:44 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2017-01-07 17:09:44 INFO     server.py:100 server start with protocol[origin] password [123123123] method [aes-256-cfb] obfs [plain] obfs_param []
2017-01-07 17:09:44 INFO     server.py:136 starting server at 0.0.0.0:9388
2017-01-07 17:09:44 ERROR    shell.py:50 'relay_rules'

客户端连接不上了。

**Comment by breakwa11** [comment]
@nickeyfff 你运行时加上 -v 显示更具体的信息

**Comment by nickeyfff** [comment]
@breakwa11   来了


python server.py  -p 9388 -k 123123123  -m aes-256-cfb -v
loaded collections.OrderedDict
IPv6 support
2017-01-08 14:15:05 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2017-01-08 14:15:05 INFO     shell.py:80 ShadowsocksR 3.0.0 2016-12-23
2017-01-08 14:15:05 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2017-01-08 14:15:05 INFO     server.py:100 server start with protocol[origin] password [123123123] method [aes-256-cfb] obfs [plain] obfs_param []
2017-01-08 14:15:05 INFO     server.py:136 starting server at 0.0.0.0:9388
2017-01-08 14:15:05 ERROR    shell.py:50 'relay_rules'
Traceback (most recent call last):
  File "server.py", line 137, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False, stat_counter=stat_counter_dict))
  File "/root/shadowsocksrss/shadowsocks/../shadowsocks/tcprelay.py", line 1258, in __init__
    self.relay_rules = self._config['relay_rules'].copy();
KeyError: 'relay_rules'
2017-01-08 14:15:05 DEBUG    eventloop.py:163 using event model: epoll

**Comment by breakwa11** [comment]
@nickeyfff 这个后端版本不支持单独运行，必须使用数据库对接

**Comment by nickeyfff** [comment]
哦了。。。原来是这样。。
