### ISSUE TITLE
服务器ssr 启动不起来什么原因额， 求助求助求助

### ISSUE THREAD

**Issue by FlyingLxy** [breakwa11/shadowsocks-rss#627]
`loaded collections.OrderedDict
Traceback (most recent call last):
  File "/usr/local/shadowsocks/shadowsocks/server.py", line 31, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/tcprelay.py", line 31, in <module>
    from shadowsocks import encrypt, obfs, eventloop, shell, common, lru_cache
  File "/usr/local/shadowsocks/shadowsocks/../shadowsocks/obfs.py", line 26, in <module>
    from shadowsocks.obfsplugin import plain, http_simple, obfs_tls, verify, auth
ImportError: cannot import name verify
ShadowsocksR start failed`

**Comment by breakwa11** [comment]
@FlyingLxy 路径shadowsocks/obfsplugin下缺少 verify.py 文件

**Comment by FlyingLxy** [comment]
@breakwa11 我是按照步骤装的，为什么会缺少文件呢？  这个文件可以单独在哪里下载吗？ 谢谢啦

**Comment by breakwa11** [comment]
@FlyingLxy 我不知道你为什么会缺少，所以请你排查一下到底是什么，还有，你用的是一键脚本安装？

**Comment by FlyingLxy** [comment]
@breakwa11 是的，用的一键安装， 我现在卡在这了……

**Comment by breakwa11** [comment]
@FlyingLxy 我的原则就是，一键安装遇到任何问题不要问我
