### ISSUE TITLE
有点不会，问一下为什么

### ISSUE THREAD

**Issue by ljwzz** [breakwa11/shadowsocks-rss#628]
bandwagon的vp::Ubuntu 16.04 x86_64  ,apt-get更新了一下，照着wiki做了一下，
userapiconfig.py已改，

python mujson_mgr.py -a -u ******* -p 8388 -k ******* -m aes-256-cfb -O auth_aes128_md5 -o tls1.2_ticket_auth

出现下面的问题，

INFO: loading config from user-config.json
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "server.py", line 39, in run
    self.obj.thread_db(self.obj)
  File "/usr/local/shadowsocksr/db_transfer.py", line 222, in thread_db
    ServerPool.get_instance()
  File "/usr/local/shadowsocksr/server_pool.py", line 68, in get_instance
    ServerPool.instance = ServerPool()
  File "/usr/local/shadowsocksr/server_pool.py", line 48, in __init__
    self.config = shell.get_config(False)
  File "/usr/local/shadowsocksr/shadowsocks/shell.py", line 311, in get_config
    check_config(config, is_local)
  File "/usr/local/shadowsocksr/shadowsocks/shell.py", line 147, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/usr/local/shadowsocksr/shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/usr/local/shadowsocksr/shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/usr/local/shadowsocksr/shadowsocks/encrypt.py", line 109, in get_cipher
    key, iv_ = EVP_BytesToKey(password, m[0], m[1])
  File "/usr/local/shadowsocksr/shadowsocks/encrypt.py", line 65, in EVP_BytesToKey
    md5.update(data)
TypeError: update() argument 1 must be string or buffer, not dict

loaded collections.OrderedDict
IPv6 support

然后似乎连不上，

[2017-01-12 10:10:05] [Warn] Proxy server [(***.***.***.***)] connection refused
[2017-01-12 10:10:05] [Error] connect to update server error
[2017-01-12 10:12:22] [Warn] Proxy server [(***.***.***.***)] connection refused

**Comment by breakwa11** [comment]
具体你到底怎么设置的，要看你的mudbjson配置文件
