### ISSUE TITLE
第一次搭建 ，遇到这个，麻烦各位帮我看一下

### ISSUE THREAD

**Issue by SuperCatss** [breakwa11/shadowsocks-rss#643]
[root@CatsIR shadowsocks]# python server.py -d start
loaded collections.OrderedDict
IPv6 support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "server.py", line 39, in run
    self.obj.thread_db(self.obj)
  File "/root/shadowsocks/db_transfer.py", line 221, in thread_db
    db_instance = obj()
  File "/root/shadowsocks/db_transfer.py", line 275, in __init__
    self.load_cfg()
  File "/root/shadowsocks/db_transfer.py", line 281, in load_cfg
    with open(config_path, 'r+') as f:
IOError: [Errno 2] No such file or directory: 'usermysql.json'

**Comment by SuperCatss** [comment]
参考的这个搭建： https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup 
使用配置文件启动的时候，就提示上面的报错了

**Comment by SuperCatss** [comment]
/root/shadowsocksr/shadowsocks
这是 目录，获取源代码以后，我初始化了配置，然后用winscp  手动修改了 socksr 下的user config 文件，然后启动 server.py  就提示了上面的报错

**Comment by SuperCatss** [comment]
另外还想问下 userconfig 和 config 这两个文件 有什么不同，两个都需要改成一样的吗？

**Comment by SuperCatss** [comment]
@breakwa11  大佬帮我看下 ，谢谢，

**Comment by hfuCN** [comment]
看 Traceback 貌似你用的是多用户，缺少数据库的配置

**Comment by SuperCatss** [comment]
谢谢，楼上，终于可以用了
