### ISSUE TITLE
按照wiki配置了mysql版本，sspanelv3mod魔改

### ISSUE THREAD

**Issue by kmahyyg** [breakwa11/shadowsocks-rss#707]
最新版本
sspanel mysql均已正常配置
ssserver.log返回的日志显示与数据库通信正常。

客户端用ip连接节点，测试连接，提示no address associated with the hostname google.com

服务端ubuntu16.04 on digitalocean
客户端安卓7.1 lineageos 其他mudbjson的节点正常

**Comment by breakwa11** [comment]
@kmahyyg 没有DNS

**Comment by kmahyyg** [comment]
这个怎么处理？手机端还是服务器端？服务器端/etc/resolv.conf是有这个的：nameserver 8.8.8.8

2017年3月22日 18:54，"破娃酱" <notifications@github.com>写道：

**Comment by breakwa11** [comment]
按wiki设置，多设置几个

**Comment by kmahyyg** [comment]
已处理。问题在sysctl.conf
没把ipv4.forwarding =1 打开。


第二个问题出现了：

在节点2配置时：
2017-03-22 08:49:32 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-03-22 08:49:32 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-03-22 08:49:32 INFO     shell.py:72 ShadowsocksR 3.1.0 2017-03-16
2017-03-22 08:49:32 INFO     db_transfer.py:232 current process RLIMIT_NOFILE resource: soft 512000 hard 512000
2017-03-22 08:49:33 ERROR    db_transfer.py:260 Traceback (most recent call last):
  File "/root/ssR/db_transfer.py", line 242, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/ssR/db_transfer.py", line 377, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/err.py", line 135, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
OperationalError: (1045, u"Access denied for user 'sspanel'@'节点2IP' (using password: YES)")

但是mysql db在节点1，而且在user-mysql.json确认设置了正确的host port pass username dbname.
userapiconfig.py使用的是glzjinmod

**Comment by kmahyyg** [comment]
换了esdeathlove的魔改后端后，问题在glzjinmod(直接与mysql通信时)仍然报错，但与modwebapi通信时正常。

虽然已经间接解决这个问题，但还是请求姐姐帮忙看下到底mysql问题在哪？

**Comment by breakwa11** [comment]
你的mysql没有权限，或密码错误

**Comment by kmahyyg** [comment]
密码确定正确，因为我是直接从mysql那台机器rsync过来之后改了host，授权检查过，都给予了all
privileges.root用户也试过，就是现在会自动把我填好的mysql host连接成127.0.0.1。。。。。。参见上面的日志。

2017年3月23日 01:13，"破娃酱" <notifications@github.com>写道：

你的mysql没有权限，或密码错误

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/breakwa11/shadowsocks-rss/issues/707#issuecomment-288471509>,
or mute the thread

**Comment by breakwa11** [comment]
@kmahyyg 权限是包含host的，这种问题你应该google mysql，而不是在这里问

**Comment by kmahyyg** [comment]
在mysql那台机器上设置host为127.0.0.1后是一切正常的。

2017年3月23日 01:57，"Patrick Young" <kmahyygyyg@gmail.com>写道：

**Comment by kmahyyg** [comment]
虽然我觉得主要的问题还是在ss这里，我觉得mysql server ip莫名其妙变成我配置的之外的，应该还是这边的问题。

**Comment by kmahyyg** [comment]
host权限使用的是 % .即可以从任意主机连接
