### ISSUE TITLE
相同的设置，ios 可以连 ubuntu客户端连不上

### ISSUE THREAD

**Issue by kt1024** [breakwa11/shadowsocks-rss#721]
相同的设置，ios 可以翻(app "Take")，ubuntu python客户端连不上，是不是json写错了？ 还是python客户端不支持某些参数？
密码是复制过去的，检查没错。服务器是刚通过git装好的。
obfs改成plain, protocol改成auth_aes_128_sha1也是一样

**服务器参数**： python3 server.py -p 443 -k password -m aes-256-cfb -O auth_sha1_v4 -o tls1.2_ticket_auth

**客户端json**：
{
        "server":"ecs ip",
        "server_port":443,
        "local_adress":"127.0.0.1",
        "local_port":"1984",
        "password":"password",
        "timeout":300,
        "method":"aes-256-cfb",
	    "protocol":"auth_sha1_v2",
        "protocolparam":"",
        "obfs":"tls1.2_ticket_auth",
        "obfsparam":"",
        "fastopen":false
}

**server debug log: (ubuntu 16.04, vultr ecs)**

2017-04-01 06:21:02 DEBUG    tcprelay.py:1123 server port   443 connections = 1
2017-04-01 06:21:02 DEBUG    tcprelay.py:1227 port 443 addr ::ffff:my wan ip connections 1
2017-04-01 06:21:02 DEBUG    tcprelay.py:1213 port 443 connections 1
2017-04-01 06:21:02 DEBUG    tcprelay.py:1236 Total connections 1
2017-04-01 06:21:02 WARNING  common.py:236 unsupported addrtype 69, maybe wrong password or encryption method
2017-04-01 06:21:02 WARNING  tcprelay.py:466 Protocol ERROR, TCP ogn data b'c95f316e7b59f840f23cf5978dba4da56fc9d789f09176cb8f0d893d1eb980638cdfd7a715a3926fd073347183ec0d36b66da9a74d7a0ade20004fd30fd5977109ab0dbb29118ce09c884501afbe2db485ba843e0a02aaef8ce94b6164948266e33a9de8f5d527ef6de3bccc983a776d527115a5e196649fddd1dbeda2d28e59aae773d78fa878be4858fd45fbfb3c250e01f90a2f3577730e169dd2d8399edf3766624c8a988763f389d62837314926c43d9ba39de11496c45b6e8bed73cc939e5d2fb022ca3e21a8316ec79d3cddc4075b6c2c19336192007617931ee55c1deb801c80916929739cd9ad2e40337ce158f3bb5b42b24c51eb0c627b' from ::ffff:my wan ip43780 via port 443 by UID 443
2017-04-01 06:21:02 ERROR    tcprelay.py:989 can not parse header when handling connection from ::ffff:my wan ip:43780
Traceback (most recent call last):
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/tcprelay.py", line 573, in _handle_stage_addr
    data = self._handel_protocol_error(self._client_address, ogn_data)
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/tcprelay.py", line 471, in _handel_protocol_error
    raise Exception('can not parse header')
Exception: can not parse header
2017-04-01 06:21:02 DEBUG    tcprelay.py:1011 destroy
2017-04-01 06:21:02 DEBUG    tcprelay.py:1031 destroying local
2017-04-01 06:21:02 DEBUG    tcprelay.py:1123 server port   443 connections = 0
2017-04-01 06:21:02 DEBUG    tcprelay.py:1227 port 443 addr ::ffff:my wan ip connections 0
2017-04-01 06:21:02 DEBUG    tcprelay.py:1213 port 443 connections 0
2017-04-01 06:21:02 DEBUG    tcprelay.py:1236 Total connections 0

**client (elementary os 0.4, ubuntu 16.04, python shadowsocks client, 2.8.2)**
2017-04-01 14:24:03 DEBUG    chosen server: ecs ip:443
2017-04-01 14:24:03 INFO     connecting clients1.google.com:443 from 127.0.0.1:32778
2017-04-01 14:24:03 DEBUG    destroy: clients1.google.com:443
2017-04-01 14:24:03 DEBUG    destroying remote
2017-04-01 14:24:03 DEBUG    destroying local

谢谢。

**Comment by breakwa11** [comment]
protocol你分明就配置的不一样

**Comment by kt1024** [comment]
改配置复制乱了而已， 测试时两端是一样的。又测试了一边都改成auth_sha1_v4，还是不行。 @breakwa11

**Comment by breakwa11** [comment]
@kt1024 服务器这个LOG表示的就是协议或加密或密码随便一个是不匹配的
