### ISSUE TITLE
python server.py出现错误Invalid control character

### ISSUE THREAD

**Issue by mooyxu** [breakwa11/shadowsocks-rss#723]
系统 lnmp，
前端 ss-panelv3，
后端 ssr manyuser，
按照流程设置的，
运行 python server.py出现错误
`ValueError: Invalid control character at: line 5 column 24 (char 88)`

**Comment by breakwa11** [comment]
非常可能是你自己搞错，麻烦帖完整

**Comment by mooyxu** [comment]
```
loaded collections.OrderedDict
IPv6 support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "server.py", line 39, in run
    self.obj.thread_db(self.obj)
  File "/home/wwwroot/ss.xxxxxxxxxxxx.com/shadowsocksr/db_transfer.py", line 226, in thread_db
    db_instance = obj()
  File "/home/wwwroot/ss.xxxxxxxxxxxx.com/shadowsocksr/db_transfer.py", line 408, in __init__
    super(Dbv3Transfer, self).__init__()
  File "/home/wwwroot/ss.xxxxxxxxxxxx.com/shadowsocksr/db_transfer.py", line 291, in __init__
    self.load_cfg()
  File "/home/wwwroot/ss.xxxxxxxxxxxx.com/shadowsocksr/db_transfer.py", line 298, in load_cfg
    cfg = json.loads(f.read().decode('utf8'))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 5 column 24 (char 88)

```

以上python server.py 结果

**Comment by breakwa11** [comment]
你配置文件格式写错了，自己改吧
