### ISSUE TITLE
Can't connect to MySQL server on u'127.0.0.1'

### ISSUE THREAD

**Issue by Yuenannn** [breakwa11/shadowsocks-rss#754]
Hi
I had installed shadowsocks, but when  I run ``python server.py -d start``, it seems that cannot access mysql. There is the ERROR log:

``` bash
2017-05-02 04:27:57 ERROR    db_transfer.py:264 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 246, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 381, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on u'127.0.0.1' (111)")
```

And there is my config file:
``` json
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "PASSWORD",
    "method": "chacha20",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {}, // only works under multi-user mode
    "additional_ports_only" : false, // only works under multi-user mode
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
```

I had already shutdown my firewalld.

Thank you!

**Comment by freedom8086** [comment]
cd ~/shadowsocksr/shadowsocks
python...............

**Comment by Yuenannn** [comment]
I'm so foolish! Thank you.
