### ISSUE TITLE
mysql多用户版建user表问题

### ISSUE THREAD

**Issue by call-fold** [breakwa11/shadowsocks-rss#855]
话说mysql多用户版的user表结构是啥, 没看到在代码里建user表啊?
2017-07-20 15:50:23 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-07-20 15:50:23 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53)]
2017-07-20 15:50:23 INFO     shell.py:72 ShadowsocksR 3.3.3 2017-06-03
2017-07-20 15:50:23 INFO     db_transfer.py:238 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2017-07-20 15:50:24 ERROR    db_transfer.py:266 Traceback (most recent call last):
  File "/opt/ssr/shadowsocksr/db_transfer.py", line 248, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/opt/ssr/shadowsocksr/db_transfer.py", line 386, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/opt/ssr/shadowsocksr/db_transfer.py", line 402, in pull_db_users
    cur.execute("SELECT " + ','.join(keys) + " FROM user")
  File "/opt/ssr/shadowsocksr/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/opt/ssr/shadowsocksr/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/opt/ssr/shadowsocksr/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'shadowsocks.user' doesn't exist")

**Comment by Ehco1996** [comment]
`SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(128) CHARACTER SET utf8mb4 NOT NULL,
  `email` varchar(32) NOT NULL,
  `pass` varchar(64) NOT NULL,
  `passwd` varchar(16) NOT NULL,
  `t` int(11) NOT NULL DEFAULT '0',
  `u` bigint(20) NOT NULL,
  `d` bigint(20) NOT NULL,
  `plan` varchar(2) CHARACTER SET utf8mb4 NOT NULL,
  `transfer_enable` bigint(20) NOT NULL,
  `port` int(11) NOT NULL,
  `switch` tinyint(4) NOT NULL DEFAULT '1',
  `enable` tinyint(4) NOT NULL DEFAULT '1',
  `type` tinyint(4) NOT NULL DEFAULT '1',
  `last_get_gift_time` int(11) NOT NULL DEFAULT '0',
  `last_check_in_time` int(11) NOT NULL DEFAULT '0',
  `last_rest_pass_time` int(11) NOT NULL DEFAULT '0',
  `reg_date` datetime NOT NULL,
  `invite_num` int(8) NOT NULL,
  `money` decimal(12,2) NOT NULL,
  `ref_by` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `user` (`uid`, `user_name`, `email`, `pass`, `passwd`, `t`, `u`, `d`, `plan`, `transfer_enable`, `port`, `switch`, `enable`, `type`, `last_get_gift_time`, `last_check_in_time`, `last_rest_pass_time`, `reg_date`, `invite_num`, `money`, `ref_by`) VALUES
(1,	'user',	'first@blood.com',	'c5a4e7e6882845ea7bb4d9462868219b',	'LoveFish',	1427454468,	25570082746,	19210700227,	'B',	385601241088,	10000,	1,	1,	7,	0,	1429758822,	0,	'1997-01-27 00:00:00',	0,	1.20,	0);

-- 2015-04-28 14:54:26
`

**Comment by call-fold** [comment]
Thanks~
